<?php

use CRM_Mailingwork_ExtensionUtil as E;

return [
  'mailingwork_fallback_campaign' => [
    'name'            => 'mailingwork_fallback_campaign',
    'type'            => 'Integer',
    'default'         => '',
    'quick_form_type' => 'Element',
    'html_type'       => 'text',
    'add'             => '4.7',
    'title'           => E::ts('Mailingwork Fallback Campaign'),
    'description'     => E::ts('Fallback campaign for Mailingwork folders with no campaign'),
    'is_domain'       => 1,
    'is_contact'      => 0,
  ],
  'mailingwork_use_mass_activities' => [
    'name'            => 'mailingwork_use_mass_activities',
    'type'            => 'Boolean',
    'default'         => TRUE,
    'quick_form_type' => 'YesNo',
    'html_type'       => 'radio',
    'add'             => '4.7',
    'title'           => E::ts('Use mass activities for Mailingwork recipients'),
    'description'     => E::ts('Whether to create (mass) activities with multiple contacts or one activity per recipient'),
    'is_domain'       => 1,
    'is_contact'      => 0,
  ],
  'mailingwork_retained_emails_last_hardbounce_from' => [
    'name'            => 'mailingwork_retained_emails_last_hardbounce_from',
    'type'            => 'String',
    'default'         => '',
    'quick_form_type' => 'Element',
    'html_type'       => 'text',
    'add'             => '4.7',
    'title'           => E::ts('Mailingwork Retained Emails Last Hardbounce From Date'),
    'description'     => E::ts('Earliest last Hardbounce date which should be imported.'),
    'is_domain'       => 1,
    'is_contact'      => 0,
  ],
  'mailingwork_optouts_start_date' => [
    'name'            => 'mailingwork_optouts_start_date',
    'type'            => 'String',
    'default'         => '',
    'quick_form_type' => 'Element',
    'html_type'       => 'text',
    'add'             => '1.2',
    'title'           => E::ts('Mailingwork: Opt-Out start date'),
    'description'     => E::ts('Date from which opt-outs should be imported.'),
    'is_domain'       => 1,
    'is_contact'      => 0,
  ],
  'mailingwork_optout_list_map' => [
    'name'        => 'mailingwork_optout_list_map',
    'type'        => 'Array',
    'html_type'   => 'text',
    'default'     => [],
    'add'         => '1.2',
    'title'       => ts('Mailingwork: Mapping of lists to groups or suppression flags for opt-outs'),
    'is_domain'   => 1,
    'is_contact'  => 0,
    'description' => ts('This maps Mailingwork lists to their corresponding group or CiviCRM suppression flag.'),
  ],
];
