<?php

/**
 * @package CRM
 * @copyright CiviCRM LLC (c) 2004-2018
 *
 * Generated from /Users/patrick/buildkit/build/gp-next/sites/default/files/civicrm/ext/at.greenpeace.mailingwork/xml/schema/CRM/Mailingwork/MailingworkMailing.xml
 * DO NOT EDIT.  Generated by CRM_Core_CodeGen
 * (GenCodeChecksum:0e0c57cd95a927de81debc267d78e4ed)
 */

/**
 * Database access object for the MailingworkMailing entity.
 */
class CRM_Mailingwork_DAO_MailingworkMailing extends CRM_Core_DAO {

  /**
   * Static instance to hold the table name.
   *
   * @var string
   */
  static $_tableName = 'civicrm_mailingwork_mailing';

  /**
   * Should CiviCRM log any modifications to this table in the civicrm_log table.
   *
   * @var bool
   */
  static $_log = TRUE;

  /**
   * Unique Mailingwork Mailing ID
   *
   * @var int unsigned
   */
  public $id;

  /**
   * Unique identifier of mailing in Mailingwork
   *
   * @var int unsigned
   */
  public $mailingwork_identifier;

  /**
   * Subject of the mailing
   *
   * @var string
   */
  public $subject;

  /**
   * Subject of the mailing
   *
   * @var text
   */
  public $description;

  /**
   * Sender name of the mailing
   *
   * @var string
   */
  public $sender_name;

  /**
   * Sender email of the mailing
   *
   * @var string
   */
  public $sender_email;

  /**
   * Mailingwork Folder ID the mailing is located in
   *
   * @var int unsigned
   */
  public $mailingwork_folder_id;

  /**
   * Date on which the mailing was sent
   *
   * @var datetime
   */
  public $sending_date;

  /**
   * Date until which recipients have been synced
   *
   * @var datetime
   */
  public $recipient_sync_date;

  /**
   * ID of sync status
   *
   * @var int unsigned
   */
  public $recipient_sync_status_id;

  /**
   * Date until which openings have been synced
   *
   * @var datetime
   */
  public $opening_sync_date;

  /**
   * ID of sync status
   *
   * @var int unsigned
   */
  public $opening_sync_status_id;

  /**
   * Date until which clicks have been synced
   *
   * @var datetime
   */
  public $click_sync_status;

  /**
   * ID of sync status
   *
   * @var int unsigned
   */
  public $click_sync_status_id;

  /**
   * ID of mailing status
   *
   * @var int unsigned
   */
  public $status_id;

  /**
   * ID of mailing type
   *
   * @var int unsigned
   */
  public $type_id;

  /**
   * Class constructor.
   */
  public function __construct() {
    $this->__table = 'civicrm_mailingwork_mailing';
    parent::__construct();
  }

  /**
   * Returns foreign keys and entity references.
   *
   * @return array
   *   [CRM_Core_Reference_Interface]
   */
  public static function getReferenceColumns() {
    if (!isset(Civi::$statics[__CLASS__]['links'])) {
      Civi::$statics[__CLASS__]['links'] = static ::createReferenceColumns(__CLASS__);
      Civi::$statics[__CLASS__]['links'][] = new CRM_Core_Reference_Basic(self::getTableName(), 'mailingwork_folder_id', 'civicrm_mailingwork_folder', 'id');
      CRM_Core_DAO_AllCoreTables::invoke(__CLASS__, 'links_callback', Civi::$statics[__CLASS__]['links']);
    }
    return Civi::$statics[__CLASS__]['links'];
  }

  /**
   * Returns all the column names of this table
   *
   * @return array
   */
  public static function &fields() {
    if (!isset(Civi::$statics[__CLASS__]['fields'])) {
      Civi::$statics[__CLASS__]['fields'] = [
        'id' => [
          'name' => 'id',
          'type' => CRM_Utils_Type::T_INT,
          'title' => ts('Mailing ID'),
          'description' => 'Unique Mailingwork Mailing ID',
          'required' => TRUE,
          'table_name' => 'civicrm_mailingwork_mailing',
          'entity' => 'MailingworkMailing',
          'bao' => 'CRM_Mailingwork_DAO_MailingworkMailing',
          'localizable' => 0,
        ],
        'mailingwork_identifier' => [
          'name' => 'mailingwork_identifier',
          'type' => CRM_Utils_Type::T_INT,
          'title' => ts('Mailingwork Identifier'),
          'description' => 'Unique identifier of mailing in Mailingwork',
          'required' => TRUE,
          'table_name' => 'civicrm_mailingwork_mailing',
          'entity' => 'MailingworkMailing',
          'bao' => 'CRM_Mailingwork_DAO_MailingworkMailing',
          'localizable' => 0,
        ],
        'subject' => [
          'name' => 'subject',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => ts('Subject'),
          'description' => 'Subject of the mailing',
          'required' => FALSE,
          'maxlength' => 998,
          'size' => CRM_Utils_Type::HUGE,
          'table_name' => 'civicrm_mailingwork_mailing',
          'entity' => 'MailingworkMailing',
          'bao' => 'CRM_Mailingwork_DAO_MailingworkMailing',
          'localizable' => 0,
          'html' => [
            'type' => 'Text',
          ],
        ],
        'description' => [
          'name' => 'description',
          'type' => CRM_Utils_Type::T_TEXT,
          'title' => ts('Description'),
          'description' => 'Subject of the mailing',
          'required' => FALSE,
          'rows' => 4,
          'cols' => 60,
          'table_name' => 'civicrm_mailingwork_mailing',
          'entity' => 'MailingworkMailing',
          'bao' => 'CRM_Mailingwork_DAO_MailingworkMailing',
          'localizable' => 0,
          'html' => [
            'type' => 'TextArea',
          ],
        ],
        'sender_name' => [
          'name' => 'sender_name',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => ts('Sender Name'),
          'description' => 'Sender name of the mailing',
          'required' => FALSE,
          'maxlength' => 255,
          'size' => CRM_Utils_Type::HUGE,
          'table_name' => 'civicrm_mailingwork_mailing',
          'entity' => 'MailingworkMailing',
          'bao' => 'CRM_Mailingwork_DAO_MailingworkMailing',
          'localizable' => 0,
          'html' => [
            'type' => 'Text',
          ],
        ],
        'sender_email' => [
          'name' => 'sender_email',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => ts('Sender Email'),
          'description' => 'Sender email of the mailing',
          'required' => FALSE,
          'maxlength' => 255,
          'size' => CRM_Utils_Type::HUGE,
          'table_name' => 'civicrm_mailingwork_mailing',
          'entity' => 'MailingworkMailing',
          'bao' => 'CRM_Mailingwork_DAO_MailingworkMailing',
          'localizable' => 0,
          'html' => [
            'type' => 'Text',
          ],
        ],
        'mailingwork_folder_id' => [
          'name' => 'mailingwork_folder_id',
          'type' => CRM_Utils_Type::T_INT,
          'title' => ts('Folder ID'),
          'description' => 'Mailingwork Folder ID the mailing is located in',
          'required' => FALSE,
          'table_name' => 'civicrm_mailingwork_mailing',
          'entity' => 'MailingworkMailing',
          'bao' => 'CRM_Mailingwork_DAO_MailingworkMailing',
          'localizable' => 0,
          'pseudoconstant' => [
            'table' => 'civicrm_mailingwork_folder',
            'keyColumn' => 'id',
            'labelColumn' => 'name',
          ]
        ],
        'sending_date' => [
          'name' => 'sending_date',
          'type' => CRM_Utils_Type::T_DATE + CRM_Utils_Type::T_TIME,
          'title' => ts('Sending Date'),
          'description' => 'Date on which the mailing was sent',
          'required' => FALSE,
          'table_name' => 'civicrm_mailingwork_mailing',
          'entity' => 'MailingworkMailing',
          'bao' => 'CRM_Mailingwork_DAO_MailingworkMailing',
          'localizable' => 0,
          'html' => [
            'type' => 'Select Date',
          ],
        ],
        'recipient_sync_date' => [
          'name' => 'recipient_sync_date',
          'type' => CRM_Utils_Type::T_DATE + CRM_Utils_Type::T_TIME,
          'title' => ts('Recipient Synchronization Date'),
          'description' => 'Date until which recipients have been synced',
          'required' => FALSE,
          'table_name' => 'civicrm_mailingwork_mailing',
          'entity' => 'MailingworkMailing',
          'bao' => 'CRM_Mailingwork_DAO_MailingworkMailing',
          'localizable' => 0,
          'html' => [
            'type' => 'Select Date',
          ],
        ],
        'recipient_sync_status_id' => [
          'name' => 'recipient_sync_status_id',
          'type' => CRM_Utils_Type::T_INT,
          'title' => ts('Recipient Synchronization Status'),
          'description' => 'ID of sync status',
          'required' => TRUE,
          'default' => '1',
          'table_name' => 'civicrm_mailingwork_mailing',
          'entity' => 'MailingworkMailing',
          'bao' => 'CRM_Mailingwork_DAO_MailingworkMailing',
          'localizable' => 0,
          'html' => [
            'type' => 'Select',
          ],
          'pseudoconstant' => [
            'optionGroupName' => 'mailingwork_mailing_sync_status',
            'optionEditPath' => 'civicrm/admin/options/mailingwork_mailing_sync_status',
          ]
        ],
        'opening_sync_date' => [
          'name' => 'opening_sync_date',
          'type' => CRM_Utils_Type::T_DATE + CRM_Utils_Type::T_TIME,
          'title' => ts('Opening Synchronization Date'),
          'description' => 'Date until which openings have been synced',
          'required' => FALSE,
          'table_name' => 'civicrm_mailingwork_mailing',
          'entity' => 'MailingworkMailing',
          'bao' => 'CRM_Mailingwork_DAO_MailingworkMailing',
          'localizable' => 0,
          'html' => [
            'type' => 'Select Date',
          ],
        ],
        'opening_sync_status_id' => [
          'name' => 'opening_sync_status_id',
          'type' => CRM_Utils_Type::T_INT,
          'title' => ts('Opening Synchronization Status'),
          'description' => 'ID of sync status',
          'required' => TRUE,
          'default' => '1',
          'table_name' => 'civicrm_mailingwork_mailing',
          'entity' => 'MailingworkMailing',
          'bao' => 'CRM_Mailingwork_DAO_MailingworkMailing',
          'localizable' => 0,
          'html' => [
            'type' => 'Select',
          ],
          'pseudoconstant' => [
            'optionGroupName' => 'mailingwork_mailing_sync_status',
            'optionEditPath' => 'civicrm/admin/options/mailingwork_mailing_sync_status',
          ]
        ],
        'click_sync_status' => [
          'name' => 'click_sync_status',
          'type' => CRM_Utils_Type::T_DATE + CRM_Utils_Type::T_TIME,
          'title' => ts('Click Synchronization Date'),
          'description' => 'Date until which clicks have been synced',
          'required' => FALSE,
          'table_name' => 'civicrm_mailingwork_mailing',
          'entity' => 'MailingworkMailing',
          'bao' => 'CRM_Mailingwork_DAO_MailingworkMailing',
          'localizable' => 0,
          'html' => [
            'type' => 'Select Date',
          ],
        ],
        'click_sync_status_id' => [
          'name' => 'click_sync_status_id',
          'type' => CRM_Utils_Type::T_INT,
          'title' => ts('Click Synchronization Status'),
          'description' => 'ID of sync status',
          'required' => TRUE,
          'default' => '1',
          'table_name' => 'civicrm_mailingwork_mailing',
          'entity' => 'MailingworkMailing',
          'bao' => 'CRM_Mailingwork_DAO_MailingworkMailing',
          'localizable' => 0,
          'html' => [
            'type' => 'Select',
          ],
          'pseudoconstant' => [
            'optionGroupName' => 'mailingwork_mailing_sync_status',
            'optionEditPath' => 'civicrm/admin/options/mailingwork_mailing_sync_status',
          ]
        ],
        'status_id' => [
          'name' => 'status_id',
          'type' => CRM_Utils_Type::T_INT,
          'title' => ts('Mailing Status'),
          'description' => 'ID of mailing status',
          'required' => TRUE,
          'table_name' => 'civicrm_mailingwork_mailing',
          'entity' => 'MailingworkMailing',
          'bao' => 'CRM_Mailingwork_DAO_MailingworkMailing',
          'localizable' => 0,
          'html' => [
            'type' => 'Select',
          ],
          'pseudoconstant' => [
            'optionGroupName' => 'mailingwork_mailing_status',
            'optionEditPath' => 'civicrm/admin/options/mailingwork_mailing_status',
          ]
        ],
        'type_id' => [
          'name' => 'type_id',
          'type' => CRM_Utils_Type::T_INT,
          'title' => ts('Mailing Type'),
          'description' => 'ID of mailing type',
          'required' => TRUE,
          'table_name' => 'civicrm_mailingwork_mailing',
          'entity' => 'MailingworkMailing',
          'bao' => 'CRM_Mailingwork_DAO_MailingworkMailing',
          'localizable' => 0,
          'html' => [
            'type' => 'Select',
          ],
          'pseudoconstant' => [
            'optionGroupName' => 'mailingwork_mailing_type',
            'optionEditPath' => 'civicrm/admin/options/mailingwork_mailing_type',
          ]
        ],
      ];
      CRM_Core_DAO_AllCoreTables::invoke(__CLASS__, 'fields_callback', Civi::$statics[__CLASS__]['fields']);
    }
    return Civi::$statics[__CLASS__]['fields'];
  }

  /**
   * Return a mapping from field-name to the corresponding key (as used in fields()).
   *
   * @return array
   *   Array(string $name => string $uniqueName).
   */
  public static function &fieldKeys() {
    if (!isset(Civi::$statics[__CLASS__]['fieldKeys'])) {
      Civi::$statics[__CLASS__]['fieldKeys'] = array_flip(CRM_Utils_Array::collect('name', self::fields()));
    }
    return Civi::$statics[__CLASS__]['fieldKeys'];
  }

  /**
   * Returns the names of this table
   *
   * @return string
   */
  public static function getTableName() {
    return self::$_tableName;
  }

  /**
   * Returns if this table needs to be logged
   *
   * @return bool
   */
  public function getLog() {
    return self::$_log;
  }

  /**
   * Returns the list of fields that can be imported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &import($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getImports(__CLASS__, 'mailingwork_mailing', $prefix, []);
    return $r;
  }

  /**
   * Returns the list of fields that can be exported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &export($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getExports(__CLASS__, 'mailingwork_mailing', $prefix, []);
    return $r;
  }

  /**
   * Returns the list of indices
   *
   * @param bool $localize
   *
   * @return array
   */
  public static function indices($localize = TRUE) {
    $indices = [
      'UI_mailingwork_identifier' => [
        'name' => 'UI_mailingwork_identifier',
        'field' => [
          0 => 'mailingwork_identifier',
        ],
        'localizable' => FALSE,
        'unique' => TRUE,
        'sig' => 'civicrm_mailingwork_mailing::1::mailingwork_identifier',
      ],
    ];
    return ($localize && !empty($indices)) ? CRM_Core_DAO_AllCoreTables::multilingualize(__CLASS__, $indices) : $indices;
  }

}
