<?php

/**
 * @package CRM
 * @copyright CiviCRM LLC https://civicrm.org/licensing
 *
 * Generated from at.greenpeace.mailingwork/xml/schema/CRM/Mailingwork/MailingworkOpening.xml
 * DO NOT EDIT.  Generated by CRM_Core_CodeGen
 * (GenCodeChecksum:e89cacdfc34b042e6c51cee82982afb2)
 */
use CRM_Mailingwork_ExtensionUtil as E;

/**
 * Database access object for the MailingworkOpening entity.
 */
class CRM_Mailingwork_DAO_MailingworkOpening extends CRM_Core_DAO {
  const EXT = E::LONG_NAME;
  const TABLE_ADDED = '';

  /**
   * Static instance to hold the table name.
   *
   * @var string
   */
  public static $_tableName = 'civicrm_mailingwork_opening';

  /**
   * Should CiviCRM log any modifications to this table in the civicrm_log table.
   *
   * @var bool
   */
  public static $_log = TRUE;

  /**
   * Unique MailingworkOpening ID
   *
   * @var int
   */
  public $id;

  /**
   * FK to ActivityContact
   *
   * @var int
   */
  public $activity_contact_id;

  /**
   * Date of the opening
   *
   * @var datetime
   */
  public $opening_date;

  /**
   * ID of user agent type
   *
   * @var int
   */
  public $user_agent_type_id;

  /**
   * ID of user agent
   *
   * @var int
   */
  public $user_agent_id;

  /**
   * Class constructor.
   */
  public function __construct() {
    $this->__table = 'civicrm_mailingwork_opening';
    parent::__construct();
  }

  /**
   * Returns localized title of this entity.
   *
   * @param bool $plural
   *   Whether to return the plural version of the title.
   */
  public static function getEntityTitle($plural = FALSE) {
    return $plural ? E::ts('Mailingwork Openings') : E::ts('Mailingwork Opening');
  }

  /**
   * Returns foreign keys and entity references.
   *
   * @return array
   *   [CRM_Core_Reference_Interface]
   */
  public static function getReferenceColumns() {
    if (!isset(Civi::$statics[__CLASS__]['links'])) {
      Civi::$statics[__CLASS__]['links'] = static::createReferenceColumns(__CLASS__);
      Civi::$statics[__CLASS__]['links'][] = new CRM_Core_Reference_Basic(self::getTableName(), 'activity_contact_id', 'civicrm_activity_contact', 'id');
      CRM_Core_DAO_AllCoreTables::invoke(__CLASS__, 'links_callback', Civi::$statics[__CLASS__]['links']);
    }
    return Civi::$statics[__CLASS__]['links'];
  }

  /**
   * Returns all the column names of this table
   *
   * @return array
   */
  public static function &fields() {
    if (!isset(Civi::$statics[__CLASS__]['fields'])) {
      Civi::$statics[__CLASS__]['fields'] = [
        'id' => [
          'name' => 'id',
          'type' => CRM_Utils_Type::T_INT,
          'description' => E::ts('Unique MailingworkOpening ID'),
          'required' => TRUE,
          'where' => 'civicrm_mailingwork_opening.id',
          'table_name' => 'civicrm_mailingwork_opening',
          'entity' => 'MailingworkOpening',
          'bao' => 'CRM_Mailingwork_DAO_MailingworkOpening',
          'localizable' => 0,
          'add' => NULL,
        ],
        'activity_contact_id' => [
          'name' => 'activity_contact_id',
          'type' => CRM_Utils_Type::T_INT,
          'description' => E::ts('FK to ActivityContact'),
          'required' => TRUE,
          'where' => 'civicrm_mailingwork_opening.activity_contact_id',
          'table_name' => 'civicrm_mailingwork_opening',
          'entity' => 'MailingworkOpening',
          'bao' => 'CRM_Mailingwork_DAO_MailingworkOpening',
          'localizable' => 0,
          'FKClassName' => 'CRM_Activity_DAO_ActivityContact',
          'add' => NULL,
        ],
        'opening_date' => [
          'name' => 'opening_date',
          'type' => CRM_Utils_Type::T_DATE + CRM_Utils_Type::T_TIME,
          'title' => E::ts('Opening Date'),
          'description' => E::ts('Date of the opening'),
          'required' => TRUE,
          'where' => 'civicrm_mailingwork_opening.opening_date',
          'table_name' => 'civicrm_mailingwork_opening',
          'entity' => 'MailingworkOpening',
          'bao' => 'CRM_Mailingwork_DAO_MailingworkOpening',
          'localizable' => 0,
          'html' => [
            'type' => 'Select Date',
          ],
          'add' => NULL,
        ],
        'user_agent_type_id' => [
          'name' => 'user_agent_type_id',
          'type' => CRM_Utils_Type::T_INT,
          'title' => E::ts('User Agent Type'),
          'description' => E::ts('ID of user agent type'),
          'required' => FALSE,
          'where' => 'civicrm_mailingwork_opening.user_agent_type_id',
          'default' => '1',
          'table_name' => 'civicrm_mailingwork_opening',
          'entity' => 'MailingworkOpening',
          'bao' => 'CRM_Mailingwork_DAO_MailingworkOpening',
          'localizable' => 0,
          'html' => [
            'type' => 'Select',
          ],
          'pseudoconstant' => [
            'optionGroupName' => 'mailingwork_user_agent_type',
            'optionEditPath' => 'civicrm/admin/options/mailingwork_user_agent_type',
          ],
          'add' => NULL,
        ],
        'user_agent_id' => [
          'name' => 'user_agent_id',
          'type' => CRM_Utils_Type::T_INT,
          'title' => E::ts('User Agent'),
          'description' => E::ts('ID of user agent'),
          'required' => FALSE,
          'where' => 'civicrm_mailingwork_opening.user_agent_id',
          'default' => '1',
          'table_name' => 'civicrm_mailingwork_opening',
          'entity' => 'MailingworkOpening',
          'bao' => 'CRM_Mailingwork_DAO_MailingworkOpening',
          'localizable' => 0,
          'html' => [
            'type' => 'Select',
          ],
          'pseudoconstant' => [
            'optionGroupName' => 'mailingwork_user_agent',
            'optionEditPath' => 'civicrm/admin/options/mailingwork_user_agent',
          ],
          'add' => NULL,
        ],
      ];
      CRM_Core_DAO_AllCoreTables::invoke(__CLASS__, 'fields_callback', Civi::$statics[__CLASS__]['fields']);
    }
    return Civi::$statics[__CLASS__]['fields'];
  }

  /**
   * Return a mapping from field-name to the corresponding key (as used in fields()).
   *
   * @return array
   *   Array(string $name => string $uniqueName).
   */
  public static function &fieldKeys() {
    if (!isset(Civi::$statics[__CLASS__]['fieldKeys'])) {
      Civi::$statics[__CLASS__]['fieldKeys'] = array_flip(CRM_Utils_Array::collect('name', self::fields()));
    }
    return Civi::$statics[__CLASS__]['fieldKeys'];
  }

  /**
   * Returns the names of this table
   *
   * @return string
   */
  public static function getTableName() {
    return self::$_tableName;
  }

  /**
   * Returns if this table needs to be logged
   *
   * @return bool
   */
  public function getLog() {
    return self::$_log;
  }

  /**
   * Returns the list of fields that can be imported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &import($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getImports(__CLASS__, 'mailingwork_opening', $prefix, []);
    return $r;
  }

  /**
   * Returns the list of fields that can be exported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &export($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getExports(__CLASS__, 'mailingwork_opening', $prefix, []);
    return $r;
  }

  /**
   * Returns the list of indices
   *
   * @param bool $localize
   *
   * @return array
   */
  public static function indices($localize = TRUE) {
    $indices = [];
    return ($localize && !empty($indices)) ? CRM_Core_DAO_AllCoreTables::multilingualize(__CLASS__, $indices) : $indices;
  }

}
