<?php

/**
 * @package CRM
 * @copyright CiviCRM LLC https://civicrm.org/licensing
 *
 * Generated from at.greenpeace.mailingwork/xml/schema/CRM/Mailingwork/MailingworkFolder.xml
 * DO NOT EDIT.  Generated by CRM_Core_CodeGen
 * (GenCodeChecksum:badd20bc3dde0fb0bedbdf67f10dfd99)
 */
use CRM_Mailingwork_ExtensionUtil as E;

/**
 * Database access object for the MailingworkFolder entity.
 */
class CRM_Mailingwork_DAO_MailingworkFolder extends CRM_Core_DAO {
  const EXT = E::LONG_NAME;
  const TABLE_ADDED = '';

  /**
   * Static instance to hold the table name.
   *
   * @var string
   */
  public static $_tableName = 'civicrm_mailingwork_folder';

  /**
   * Should CiviCRM log any modifications to this table in the civicrm_log table.
   *
   * @var bool
   */
  public static $_log = TRUE;

  /**
   * Unique Mailingwork Folder ID
   *
   * @var int|string|null
   *   (SQL type: int unsigned)
   *   Note that values will be retrieved from the database as a string.
   */
  public $id;

  /**
   * Unique identifier of folder in Mailingwork
   *
   * @var int|string
   *   (SQL type: int unsigned)
   *   Note that values will be retrieved from the database as a string.
   */
  public $mailingwork_identifier;

  /**
   * Parent folder
   *
   * @var int|string
   *   (SQL type: int unsigned)
   *   Note that values will be retrieved from the database as a string.
   */
  public $parent_id;

  /**
   * Folder name
   *
   * @var string
   *   (SQL type: varchar(255))
   *   Note that values will be retrieved from the database as a string.
   */
  public $name;

  /**
   * Campaign ID associated with mailings in this folder.
   *
   * @var int|string
   *   (SQL type: int unsigned)
   *   Note that values will be retrieved from the database as a string.
   */
  public $campaign_id;

  /**
   * Class constructor.
   */
  public function __construct() {
    $this->__table = 'civicrm_mailingwork_folder';
    parent::__construct();
  }

  /**
   * Returns localized title of this entity.
   *
   * @param bool $plural
   *   Whether to return the plural version of the title.
   */
  public static function getEntityTitle($plural = FALSE) {
    return $plural ? E::ts('Mailingwork Folders') : E::ts('Mailingwork Folder');
  }

  /**
   * Returns foreign keys and entity references.
   *
   * @return array
   *   [CRM_Core_Reference_Interface]
   */
  public static function getReferenceColumns() {
    if (!isset(Civi::$statics[__CLASS__]['links'])) {
      Civi::$statics[__CLASS__]['links'] = static::createReferenceColumns(__CLASS__);
      Civi::$statics[__CLASS__]['links'][] = new CRM_Core_Reference_Basic(self::getTableName(), 'parent_id', 'civicrm_mailingwork_folder', 'id');
      Civi::$statics[__CLASS__]['links'][] = new CRM_Core_Reference_Basic(self::getTableName(), 'campaign_id', 'civicrm_campaign', 'id');
      CRM_Core_DAO_AllCoreTables::invoke(__CLASS__, 'links_callback', Civi::$statics[__CLASS__]['links']);
    }
    return Civi::$statics[__CLASS__]['links'];
  }

  /**
   * Returns all the column names of this table
   *
   * @return array
   */
  public static function &fields() {
    if (!isset(Civi::$statics[__CLASS__]['fields'])) {
      Civi::$statics[__CLASS__]['fields'] = [
        'id' => [
          'name' => 'id',
          'type' => CRM_Utils_Type::T_INT,
          'title' => E::ts('Folder ID'),
          'description' => E::ts('Unique Mailingwork Folder ID'),
          'required' => TRUE,
          'where' => 'civicrm_mailingwork_folder.id',
          'table_name' => 'civicrm_mailingwork_folder',
          'entity' => 'MailingworkFolder',
          'bao' => 'CRM_Mailingwork_DAO_MailingworkFolder',
          'localizable' => 0,
          'readonly' => TRUE,
          'add' => NULL,
        ],
        'mailingwork_identifier' => [
          'name' => 'mailingwork_identifier',
          'type' => CRM_Utils_Type::T_INT,
          'title' => E::ts('Mailingwork Identifier'),
          'description' => E::ts('Unique identifier of folder in Mailingwork'),
          'required' => TRUE,
          'where' => 'civicrm_mailingwork_folder.mailingwork_identifier',
          'table_name' => 'civicrm_mailingwork_folder',
          'entity' => 'MailingworkFolder',
          'bao' => 'CRM_Mailingwork_DAO_MailingworkFolder',
          'localizable' => 0,
          'add' => NULL,
        ],
        'parent_id' => [
          'name' => 'parent_id',
          'type' => CRM_Utils_Type::T_INT,
          'title' => E::ts('Parent Folder ID'),
          'description' => E::ts('Parent folder'),
          'required' => FALSE,
          'where' => 'civicrm_mailingwork_folder.parent_id',
          'table_name' => 'civicrm_mailingwork_folder',
          'entity' => 'MailingworkFolder',
          'bao' => 'CRM_Mailingwork_DAO_MailingworkFolder',
          'localizable' => 0,
          'FKClassName' => 'CRM_Mailingwork_DAO_MailingworkFolder',
          'pseudoconstant' => [
            'table' => 'civicrm_mailingwork_folder',
            'keyColumn' => 'id',
            'labelColumn' => 'name',
          ],
          'add' => NULL,
        ],
        'name' => [
          'name' => 'name',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => E::ts('Folder Name'),
          'description' => E::ts('Folder name'),
          'required' => FALSE,
          'maxlength' => 255,
          'size' => CRM_Utils_Type::HUGE,
          'where' => 'civicrm_mailingwork_folder.name',
          'table_name' => 'civicrm_mailingwork_folder',
          'entity' => 'MailingworkFolder',
          'bao' => 'CRM_Mailingwork_DAO_MailingworkFolder',
          'localizable' => 0,
          'html' => [
            'type' => 'Text',
          ],
          'add' => NULL,
        ],
        'campaign_id' => [
          'name' => 'campaign_id',
          'type' => CRM_Utils_Type::T_INT,
          'title' => E::ts('Campaign'),
          'description' => E::ts('Campaign ID associated with mailings in this folder.'),
          'required' => FALSE,
          'where' => 'civicrm_mailingwork_folder.campaign_id',
          'table_name' => 'civicrm_mailingwork_folder',
          'entity' => 'MailingworkFolder',
          'bao' => 'CRM_Mailingwork_DAO_MailingworkFolder',
          'localizable' => 0,
          'FKClassName' => 'CRM_Campaign_DAO_Campaign',
          'pseudoconstant' => [
            'table' => 'civicrm_campaign',
            'keyColumn' => 'id',
            'labelColumn' => 'title',
          ],
          'add' => NULL,
        ],
      ];
      CRM_Core_DAO_AllCoreTables::invoke(__CLASS__, 'fields_callback', Civi::$statics[__CLASS__]['fields']);
    }
    return Civi::$statics[__CLASS__]['fields'];
  }

  /**
   * Return a mapping from field-name to the corresponding key (as used in fields()).
   *
   * @return array
   *   Array(string $name => string $uniqueName).
   */
  public static function &fieldKeys() {
    if (!isset(Civi::$statics[__CLASS__]['fieldKeys'])) {
      Civi::$statics[__CLASS__]['fieldKeys'] = array_flip(CRM_Utils_Array::collect('name', self::fields()));
    }
    return Civi::$statics[__CLASS__]['fieldKeys'];
  }

  /**
   * Returns the names of this table
   *
   * @return string
   */
  public static function getTableName() {
    return self::$_tableName;
  }

  /**
   * Returns if this table needs to be logged
   *
   * @return bool
   */
  public function getLog() {
    return self::$_log;
  }

  /**
   * Returns the list of fields that can be imported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &import($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getImports(__CLASS__, 'mailingwork_folder', $prefix, []);
    return $r;
  }

  /**
   * Returns the list of fields that can be exported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &export($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getExports(__CLASS__, 'mailingwork_folder', $prefix, []);
    return $r;
  }

  /**
   * Returns the list of indices
   *
   * @param bool $localize
   *
   * @return array
   */
  public static function indices($localize = TRUE) {
    $indices = [
      'UI_mailingwork_identifier' => [
        'name' => 'UI_mailingwork_identifier',
        'field' => [
          0 => 'mailingwork_identifier',
        ],
        'localizable' => FALSE,
        'unique' => TRUE,
        'sig' => 'civicrm_mailingwork_folder::1::mailingwork_identifier',
      ],
    ];
    return ($localize && !empty($indices)) ? CRM_Core_DAO_AllCoreTables::multilingualize(__CLASS__, $indices) : $indices;
  }

}
