<?php

/**
 * @package CRM
 * @copyright CiviCRM LLC https://civicrm.org/licensing
 *
 * Generated from at.greenpeace.mailingwork/xml/schema/CRM/Mailingwork/MailingworkLink.xml
 * DO NOT EDIT.  Generated by CRM_Core_CodeGen
 * (GenCodeChecksum:a655c04b15bace0ebb040c88531a1b3b)
 */
use CRM_Mailingwork_ExtensionUtil as E;

/**
 * Database access object for the MailingworkLink entity.
 */
class CRM_Mailingwork_DAO_MailingworkLink extends CRM_Core_DAO {
  const EXT = E::LONG_NAME;
  const TABLE_ADDED = '';

  /**
   * Static instance to hold the table name.
   *
   * @var string
   */
  public static $_tableName = 'civicrm_mailingwork_link';

  /**
   * Should CiviCRM log any modifications to this table in the civicrm_log table.
   *
   * @var bool
   */
  public static $_log = TRUE;

  /**
   * Unique MailingworkLink ID
   *
   * @var int|string|null
   *   (SQL type: int unsigned)
   *   Note that values will be retrieved from the database as a string.
   */
  public $id;

  /**
   * URL of the Link
   *
   * @var string
   *   (SQL type: varchar(1023))
   *   Note that values will be retrieved from the database as a string.
   */
  public $url;

  /**
   * Unique Identifier used by Mailingwork
   *
   * @var int|string
   *   (SQL type: int unsigned)
   *   Note that values will be retrieved from the database as a string.
   */
  public $mailingwork_id;

  /**
   * FK to MailinkworkMailing
   *
   * @var int|string
   *   (SQL type: int unsigned)
   *   Note that values will be retrieved from the database as a string.
   */
  public $mailing_id;

  /**
   * Class constructor.
   */
  public function __construct() {
    $this->__table = 'civicrm_mailingwork_link';
    parent::__construct();
  }

  /**
   * Returns localized title of this entity.
   *
   * @param bool $plural
   *   Whether to return the plural version of the title.
   */
  public static function getEntityTitle($plural = FALSE) {
    return $plural ? E::ts('Mailingwork Links') : E::ts('Mailingwork Link');
  }

  /**
   * Returns foreign keys and entity references.
   *
   * @return array
   *   [CRM_Core_Reference_Interface]
   */
  public static function getReferenceColumns() {
    if (!isset(Civi::$statics[__CLASS__]['links'])) {
      Civi::$statics[__CLASS__]['links'] = static::createReferenceColumns(__CLASS__);
      Civi::$statics[__CLASS__]['links'][] = new CRM_Core_Reference_Basic(self::getTableName(), 'mailing_id', 'civicrm_mailingwork_mailing', 'id');
      CRM_Core_DAO_AllCoreTables::invoke(__CLASS__, 'links_callback', Civi::$statics[__CLASS__]['links']);
    }
    return Civi::$statics[__CLASS__]['links'];
  }

  /**
   * Returns all the column names of this table
   *
   * @return array
   */
  public static function &fields() {
    if (!isset(Civi::$statics[__CLASS__]['fields'])) {
      Civi::$statics[__CLASS__]['fields'] = [
        'id' => [
          'name' => 'id',
          'type' => CRM_Utils_Type::T_INT,
          'title' => E::ts('Link ID'),
          'description' => E::ts('Unique MailingworkLink ID'),
          'required' => TRUE,
          'where' => 'civicrm_mailingwork_link.id',
          'table_name' => 'civicrm_mailingwork_link',
          'entity' => 'MailingworkLink',
          'bao' => 'CRM_Mailingwork_DAO_MailingworkLink',
          'localizable' => 0,
          'html' => [
            'type' => 'Number',
          ],
          'readonly' => TRUE,
          'add' => NULL,
        ],
        'url' => [
          'name' => 'url',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => E::ts('URL'),
          'description' => E::ts('URL of the Link'),
          'required' => FALSE,
          'maxlength' => 1023,
          'size' => CRM_Utils_Type::HUGE,
          'where' => 'civicrm_mailingwork_link.url',
          'table_name' => 'civicrm_mailingwork_link',
          'entity' => 'MailingworkLink',
          'bao' => 'CRM_Mailingwork_DAO_MailingworkLink',
          'localizable' => 0,
          'html' => [
            'type' => 'Text',
          ],
          'add' => NULL,
        ],
        'mailingwork_id' => [
          'name' => 'mailingwork_id',
          'type' => CRM_Utils_Type::T_INT,
          'title' => E::ts('Mailingwork ID'),
          'description' => E::ts('Unique Identifier used by Mailingwork'),
          'required' => TRUE,
          'where' => 'civicrm_mailingwork_link.mailingwork_id',
          'table_name' => 'civicrm_mailingwork_link',
          'entity' => 'MailingworkLink',
          'bao' => 'CRM_Mailingwork_DAO_MailingworkLink',
          'localizable' => 0,
          'html' => [
            'type' => 'Number',
          ],
          'add' => NULL,
        ],
        'mailing_id' => [
          'name' => 'mailing_id',
          'type' => CRM_Utils_Type::T_INT,
          'title' => E::ts('Mailing ID'),
          'description' => E::ts('FK to MailinkworkMailing'),
          'required' => TRUE,
          'where' => 'civicrm_mailingwork_link.mailing_id',
          'table_name' => 'civicrm_mailingwork_link',
          'entity' => 'MailingworkLink',
          'bao' => 'CRM_Mailingwork_DAO_MailingworkLink',
          'localizable' => 0,
          'FKClassName' => 'CRM_Mailingwork_DAO_MailingworkMailing',
          'html' => [
            'type' => 'Number',
          ],
          'add' => NULL,
        ],
      ];
      CRM_Core_DAO_AllCoreTables::invoke(__CLASS__, 'fields_callback', Civi::$statics[__CLASS__]['fields']);
    }
    return Civi::$statics[__CLASS__]['fields'];
  }

  /**
   * Return a mapping from field-name to the corresponding key (as used in fields()).
   *
   * @return array
   *   Array(string $name => string $uniqueName).
   */
  public static function &fieldKeys() {
    if (!isset(Civi::$statics[__CLASS__]['fieldKeys'])) {
      Civi::$statics[__CLASS__]['fieldKeys'] = array_flip(CRM_Utils_Array::collect('name', self::fields()));
    }
    return Civi::$statics[__CLASS__]['fieldKeys'];
  }

  /**
   * Returns the names of this table
   *
   * @return string
   */
  public static function getTableName() {
    return self::$_tableName;
  }

  /**
   * Returns if this table needs to be logged
   *
   * @return bool
   */
  public function getLog() {
    return self::$_log;
  }

  /**
   * Returns the list of fields that can be imported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &import($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getImports(__CLASS__, 'mailingwork_link', $prefix, []);
    return $r;
  }

  /**
   * Returns the list of fields that can be exported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &export($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getExports(__CLASS__, 'mailingwork_link', $prefix, []);
    return $r;
  }

  /**
   * Returns the list of indices
   *
   * @param bool $localize
   *
   * @return array
   */
  public static function indices($localize = TRUE) {
    $indices = [];
    return ($localize && !empty($indices)) ? CRM_Core_DAO_AllCoreTables::multilingualize(__CLASS__, $indices) : $indices;
  }

}
