-- +--------------------------------------------------------------------+
-- | Copyright CiviCRM LLC. All rights reserved.                        |
-- |                                                                    |
-- | This work is published under the GNU AGPLv3 license with some      |
-- | permitted exceptions and without any warranty. For full license    |
-- | and copyright information, see https://civicrm.org/licensing       |
-- +--------------------------------------------------------------------+
--
-- Generated from schema.tpl
-- DO NOT EDIT.  Generated by CRM_Core_CodeGen
--
-- /*******************************************************
-- *
-- * Clean up the existing tables - this section generated from drop.tpl
-- *
-- *******************************************************/

SET FOREIGN_KEY_CHECKS=0;

DROP TABLE IF EXISTS `civicrm_mailingwork_link_interest`;
DROP TABLE IF EXISTS `civicrm_mailingwork_link`;
DROP TABLE IF EXISTS `civicrm_mailingwork_opening`;
DROP TABLE IF EXISTS `civicrm_mailingwork_mailing`;
DROP TABLE IF EXISTS `civicrm_mailingwork_interest`;
DROP TABLE IF EXISTS `civicrm_mailingwork_folder`;
DROP TABLE IF EXISTS `civicrm_activity_contact_email`;

SET FOREIGN_KEY_CHECKS=1;
-- /*******************************************************
-- *
-- * Create new tables
-- *
-- *******************************************************/

-- /*******************************************************
-- *
-- * civicrm_activity_contact_email
-- *
-- *******************************************************/
CREATE TABLE `civicrm_activity_contact_email` (
  `id` int unsigned NOT NULL AUTO_INCREMENT COMMENT 'Unique ActivityContactEmail ID',
  `activity_contact_id` int unsigned NOT NULL COMMENT 'FK to ActivityContact',
  `email` varchar(255) NULL COMMENT 'email used to communicate with the contact',
  PRIMARY KEY (`id`),
  CONSTRAINT FK_civicrm_activity_contact_email_activity_contact_id FOREIGN KEY (`activity_contact_id`) REFERENCES `civicrm_activity_contact`(`id`) ON DELETE CASCADE
)
ENGINE=InnoDB;

-- /*******************************************************
-- *
-- * civicrm_mailingwork_folder
-- *
-- *******************************************************/
CREATE TABLE `civicrm_mailingwork_folder` (
  `id` int unsigned NOT NULL AUTO_INCREMENT COMMENT 'Unique Mailingwork Folder ID',
  `mailingwork_identifier` int unsigned NOT NULL COMMENT 'Unique identifier of folder in Mailingwork',
  `parent_id` int unsigned NULL COMMENT 'Parent folder',
  `name` varchar(255) NULL COMMENT 'Folder name',
  `campaign_id` int unsigned NULL COMMENT 'Campaign ID associated with mailings in this folder.',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `UI_mailingwork_identifier`(mailingwork_identifier),
  CONSTRAINT FK_civicrm_mailingwork_folder_parent_id FOREIGN KEY (`parent_id`) REFERENCES `civicrm_mailingwork_folder`(`id`) ON DELETE SET NULL,
  CONSTRAINT FK_civicrm_mailingwork_folder_campaign_id FOREIGN KEY (`campaign_id`) REFERENCES `civicrm_campaign`(`id`) ON DELETE SET NULL
)
ENGINE=InnoDB;

-- /*******************************************************
-- *
-- * civicrm_mailingwork_interest
-- *
-- *******************************************************/
CREATE TABLE `civicrm_mailingwork_interest` (
  `id` int unsigned NOT NULL AUTO_INCREMENT COMMENT 'Unique MailingworkInterest ID',
  `name` varchar(255) NULL COMMENT 'Name of the Interest',
  `mailingwork_id` int unsigned NOT NULL COMMENT 'Unique Identifier used by Mailingwork',
  PRIMARY KEY (`id`)
)
ENGINE=InnoDB;

-- /*******************************************************
-- *
-- * civicrm_mailingwork_mailing
-- *
-- *******************************************************/
CREATE TABLE `civicrm_mailingwork_mailing` (
  `id` int unsigned NOT NULL AUTO_INCREMENT COMMENT 'Unique Mailingwork Mailing ID',
  `mailingwork_identifier` int unsigned NOT NULL COMMENT 'Unique identifier of mailing in Mailingwork',
  `subject` varchar(998) NULL COMMENT 'Subject of the mailing',
  `description` text NULL COMMENT 'Subject of the mailing',
  `sender_name` varchar(255) NULL COMMENT 'Sender name of the mailing',
  `sender_email` varchar(255) NULL COMMENT 'Sender email of the mailing',
  `mailingwork_folder_id` int unsigned NULL COMMENT 'Mailingwork Folder ID the mailing is located in',
  `sending_date` datetime NULL COMMENT 'Date on which the mailing was sent',
  `recipient_sync_date` datetime NULL COMMENT 'Date until which recipients have been synced',
  `recipient_sync_status_id` int unsigned NOT NULL DEFAULT 1 COMMENT 'ID of sync status',
  `opening_sync_date` datetime NULL COMMENT 'Date until which openings have been synced',
  `opening_sync_status_id` int unsigned NOT NULL DEFAULT 1 COMMENT 'ID of sync status',
  `click_sync_date` datetime NULL COMMENT 'Date until which clicks have been synced',
  `click_sync_status_id` int unsigned NOT NULL DEFAULT 1 COMMENT 'ID of sync status',
  `bounce_sync_date` datetime NULL COMMENT 'Date until which bounces have been synced',
  `bounce_sync_status_id` int unsigned NOT NULL DEFAULT 1 COMMENT 'ID of sync status',
  `status_id` int unsigned NOT NULL COMMENT 'ID of mailing status',
  `type_id` int unsigned NOT NULL COMMENT 'ID of mailing type',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `UI_mailingwork_identifier`(mailingwork_identifier),
  CONSTRAINT FK_civicrm_mailingwork_mailing_mailingwork_folder_id FOREIGN KEY (`mailingwork_folder_id`) REFERENCES `civicrm_mailingwork_folder`(`id`) ON DELETE SET NULL
)
ENGINE=InnoDB;

-- /*******************************************************
-- *
-- * civicrm_mailingwork_opening
-- *
-- *******************************************************/
CREATE TABLE `civicrm_mailingwork_opening` (
  `id` int unsigned NOT NULL AUTO_INCREMENT COMMENT 'Unique MailingworkOpening ID',
  `activity_contact_id` int unsigned NOT NULL COMMENT 'FK to ActivityContact',
  `opening_date` datetime NOT NULL COMMENT 'Date of the opening',
  `user_agent_type_id` int unsigned NULL DEFAULT 1 COMMENT 'ID of user agent type',
  `user_agent_id` int unsigned NULL DEFAULT 1 COMMENT 'ID of user agent',
  PRIMARY KEY (`id`),
  CONSTRAINT FK_civicrm_mailingwork_opening_activity_contact_id FOREIGN KEY (`activity_contact_id`) REFERENCES `civicrm_activity_contact`(`id`) ON DELETE CASCADE
)
ENGINE=InnoDB;

-- /*******************************************************
-- *
-- * civicrm_mailingwork_link
-- *
-- *******************************************************/
CREATE TABLE `civicrm_mailingwork_link` (
  `id` int unsigned NOT NULL AUTO_INCREMENT COMMENT 'Unique MailingworkLink ID',
  `url` varchar(1023) NULL COMMENT 'URL of the Link',
  `mailingwork_id` int unsigned NOT NULL COMMENT 'Unique Identifier used by Mailingwork',
  `mailing_id` int unsigned NOT NULL COMMENT 'FK to MailingworkMailing',
  PRIMARY KEY (`id`),
  CONSTRAINT FK_civicrm_mailingwork_link_mailing_id FOREIGN KEY (`mailing_id`) REFERENCES `civicrm_mailingwork_mailing`(`id`) ON DELETE CASCADE
)
ENGINE=InnoDB;

-- /*******************************************************
-- *
-- * civicrm_mailingwork_link_interest
-- *
-- *******************************************************/
CREATE TABLE `civicrm_mailingwork_link_interest` (
  `id` int unsigned NOT NULL AUTO_INCREMENT COMMENT 'Unique MailingworkLinkInterest ID',
  `link_id` int unsigned NOT NULL COMMENT 'FK to MailingworkLink',
  `interest_id` int unsigned NOT NULL COMMENT 'FK to MailingworkInterest',
  PRIMARY KEY (`id`),
  CONSTRAINT FK_civicrm_mailingwork_link_interest_link_id FOREIGN KEY (`link_id`) REFERENCES `civicrm_mailingwork_link`(`id`) ON DELETE CASCADE,
  CONSTRAINT FK_civicrm_mailingwork_link_interest_interest_id FOREIGN KEY (`interest_id`) REFERENCES `civicrm_mailingwork_interest`(`id`) ON DELETE CASCADE
)
ENGINE=InnoDB;
