-- +--------------------------------------------------------------------+
-- | CiviCRM version 5                                                  |
-- +--------------------------------------------------------------------+
-- | Copyright CiviCRM LLC (c) 2004-2018                                |
-- +--------------------------------------------------------------------+
-- | This file is a part of CiviCRM.                                    |
-- |                                                                    |
-- | CiviCRM is free software; you can copy, modify, and distribute it  |
-- | under the terms of the GNU Affero General Public License           |
-- | Version 3, 19 November 2007 and the CiviCRM Licensing Exception.   |
-- |                                                                    |
-- | CiviCRM is distributed in the hope that it will be useful, but     |
-- | WITHOUT ANY WARRANTY; without even the implied warranty of         |
-- | MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.               |
-- | See the GNU Affero General Public License for more details.        |
-- |                                                                    |
-- | You should have received a copy of the GNU Affero General Public   |
-- | License and the CiviCRM Licensing Exception along                  |
-- | with this program; if not, contact CiviCRM LLC                     |
-- | at info[AT]civicrm[DOT]org. If you have questions about the        |
-- | GNU Affero General Public License or the licensing of CiviCRM,     |
-- | see the CiviCRM license FAQ at http://civicrm.org/licensing        |
-- +--------------------------------------------------------------------+
--
-- Generated from schema.tpl
-- DO NOT EDIT.  Generated by CRM_Core_CodeGen
--


-- +--------------------------------------------------------------------+
-- | CiviCRM version 5                                                  |
-- +--------------------------------------------------------------------+
-- | Copyright CiviCRM LLC (c) 2004-2018                                |
-- +--------------------------------------------------------------------+
-- | This file is a part of CiviCRM.                                    |
-- |                                                                    |
-- | CiviCRM is free software; you can copy, modify, and distribute it  |
-- | under the terms of the GNU Affero General Public License           |
-- | Version 3, 19 November 2007 and the CiviCRM Licensing Exception.   |
-- |                                                                    |
-- | CiviCRM is distributed in the hope that it will be useful, but     |
-- | WITHOUT ANY WARRANTY; without even the implied warranty of         |
-- | MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.               |
-- | See the GNU Affero General Public License for more details.        |
-- |                                                                    |
-- | You should have received a copy of the GNU Affero General Public   |
-- | License and the CiviCRM Licensing Exception along                  |
-- | with this program; if not, contact CiviCRM LLC                     |
-- | at info[AT]civicrm[DOT]org. If you have questions about the        |
-- | GNU Affero General Public License or the licensing of CiviCRM,     |
-- | see the CiviCRM license FAQ at http://civicrm.org/licensing        |
-- +--------------------------------------------------------------------+
--
-- Generated from drop.tpl
-- DO NOT EDIT.  Generated by CRM_Core_CodeGen
--
-- /*******************************************************
-- *
-- * Clean up the exisiting tables
-- *
-- *******************************************************/

SET FOREIGN_KEY_CHECKS=0;

DROP TABLE IF EXISTS `civicrm_mailingwork_mailing`;
DROP TABLE IF EXISTS `civicrm_mailingwork_folder`;
DROP TABLE IF EXISTS `civicrm_activity_contact_email`;

SET FOREIGN_KEY_CHECKS=1;
-- /*******************************************************
-- *
-- * Create new tables
-- *
-- *******************************************************/

-- /*******************************************************
-- *
-- * civicrm_activity_contact_email
-- *
-- *******************************************************/
CREATE TABLE `civicrm_activity_contact_email` (


     `id` int unsigned NOT NULL AUTO_INCREMENT  COMMENT 'Unique ActivityContactEmail ID',
     `activity_contact_id` int unsigned    COMMENT 'FK to ActivityContact',
     `email` varchar(255) NULL   COMMENT 'email used to communicate with the contact' 
,
        PRIMARY KEY (`id`)
 
 
,          CONSTRAINT FK_civicrm_activity_contact_email_activity_contact_id FOREIGN KEY (`activity_contact_id`) REFERENCES `civicrm_activity_contact`(`id`) ON DELETE CASCADE  
)    ;

-- /*******************************************************
-- *
-- * civicrm_mailingwork_folder
-- *
-- *******************************************************/
CREATE TABLE `civicrm_mailingwork_folder` (


     `id` int unsigned NOT NULL AUTO_INCREMENT  COMMENT 'Unique Mailingwork Folder ID',
     `mailingwork_identifier` int unsigned NOT NULL   COMMENT 'Unique identifier of folder in Mailingwork',
     `parent_id` int unsigned NULL   COMMENT 'Parent folder',
     `name` varchar(255) NULL   COMMENT 'Folder name',
     `campaign_id` int unsigned NULL   COMMENT 'Campaign ID associated with mailings in this folder.' 
,
        PRIMARY KEY (`id`)
 
    ,     UNIQUE INDEX `UI_mailingwork_identifier`(
        mailingwork_identifier
  )
  
,          CONSTRAINT FK_civicrm_mailingwork_folder_parent_id FOREIGN KEY (`parent_id`) REFERENCES `civicrm_mailingwork_folder`(`id`) ON DELETE SET NULL,          CONSTRAINT FK_civicrm_mailingwork_folder_campaign_id FOREIGN KEY (`campaign_id`) REFERENCES `civicrm_campaign`(`id`) ON DELETE SET NULL  
)    ;

-- /*******************************************************
-- *
-- * civicrm_mailingwork_mailing
-- *
-- *******************************************************/
CREATE TABLE `civicrm_mailingwork_mailing` (


     `id` int unsigned NOT NULL AUTO_INCREMENT  COMMENT 'Unique Mailingwork Mailing ID',
     `mailingwork_identifier` int unsigned NOT NULL   COMMENT 'Unique identifier of mailing in Mailingwork',
     `subject` varchar(998) NULL   COMMENT 'Subject of the mailing',
     `description` text NULL   COMMENT 'Subject of the mailing',
     `sender_name` varchar(255) NULL   COMMENT 'Sender name of the mailing',
     `sender_email` varchar(255) NULL   COMMENT 'Sender email of the mailing',
     `mailingwork_folder_id` int unsigned NULL   COMMENT 'Mailingwork Folder ID the mailing is located in',
     `sending_date` datetime NULL   COMMENT 'Date on which the mailing was sent',
     `recipient_sync_date` datetime NULL   COMMENT 'Date until which recipients have been synced',
     `recipient_sync_status_id` int unsigned NOT NULL  DEFAULT 1 COMMENT 'ID of sync status',
     `opening_sync_date` datetime NULL   COMMENT 'Date until which openings have been synced',
     `opening_sync_status_id` int unsigned NOT NULL  DEFAULT 1 COMMENT 'ID of sync status',
     `click_sync_date` datetime NULL   COMMENT 'Date until which clicks have been synced',
     `click_sync_status_id` int unsigned NOT NULL  DEFAULT 1 COMMENT 'ID of sync status',
     `status_id` int unsigned NOT NULL   COMMENT 'ID of mailing status',
     `type_id` int unsigned NOT NULL   COMMENT 'ID of mailing type' 
,
        PRIMARY KEY (`id`)
 
    ,     UNIQUE INDEX `UI_mailingwork_identifier`(
        mailingwork_identifier
  )
  
,          CONSTRAINT FK_civicrm_mailingwork_mailing_mailingwork_folder_id FOREIGN KEY (`mailingwork_folder_id`) REFERENCES `civicrm_mailingwork_folder`(`id`) ON DELETE SET NULL  
)    ;

 
